# Generated by Django 6.0.2 on 2026-04-22 10:00

import django.core.validators
import sneakers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_favorite_and_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, help_text='Фото кроссовок для карточки в каталоге.', null=True, upload_to=sneakers.models.sneaker_image_upload_to, verbose_name='Картинка для каталога'),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='model_file',
            field=models.FileField(blank=True, help_text='Рекомендуемый формат: .glb, потому что он хранит модель и текстуры в одном файле.', null=True, upload_to=sneakers.models.sneaker_model_upload_to, validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf'])], verbose_name='Файл 3D модели'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='model_path',
            field=models.CharField(blank=True, default='sneakers/models/scene.gltf', help_text='Запасной вариант для моделей, которые уже лежат в static. Например: sneakers/models/scene.gltf', max_length=220, verbose_name='Путь к 3D модели в static'),
        ),
    ]
