# Generated by Django 6.0.2 on 2026-04-22 10:01

import django.core.validators
import sneakers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_sneaker_image_sneaker_model_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='model_file',
            field=models.FileField(blank=True, help_text='Загрузите .glb файл. Этот формат хранит модель и текстуры в одном файле.', null=True, upload_to=sneakers.models.sneaker_model_upload_to, validators=[django.core.validators.FileExtensionValidator(['glb'])], verbose_name='Файл 3D модели'),
        ),
    ]
